In [3]:
import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/life-expectancy.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/life-expectancy.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

In [4]:
df.head()

        entity code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138
3  Afghanistan  AFG  1953            29.4521
4  Afghanistan  AFG  1954            29.6975

In [5]:
df.rename(columns={"entity": "Pais"}, inplace=True)
df.rename(columns={"year": "anio"}, inplace=True)
df.rename(columns={"life_expectancy_0": "Esperanza_De_Vida"}, inplace=True)
df.head(3)

          Pais code  anio  Esperanza_De_Vida
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138

In [6]:
##df.set_index("Pais")

In [7]:
df.loc[df["Pais"].str.contains("UNI", case=False, regex=True)]

                               Pais code  anio  Esperanza_De_Vida
15803                       Reunion  REU  1950            47.5602
15804                       Reunion  REU  1951            48.6476
15805                       Reunion  REU  1952            50.1082
15806                       Reunion  REU  1953            51.4650
15807                       Reunion  REU  1954            52.9912
...                             ...  ...   ...                ...
20581  United States Virgin Islands  VIR  2019            74.8761
20582  United States Virgin Islands  VIR  2020            74.7137
20583  United States Virgin Islands  VIR  2021            74.6132
20584  United States Virgin Islands  VIR  2022            75.0449
20585  United States Virgin Islands  VIR  2023            75.4724

[666 rows x 4 columns]

In [8]:
df.dropna(subset=["code"], inplace=True)

In [11]:
resultado = (
    df.groupby("Pais")["Esperanza_De_Vida"]
    .mean()
    .sort_values(ascending=True)
)

resultado

Pais
USSR             32.700000
South Sudan      37.841631
Sierra Leone     43.189605
Mali             43.760793
Niger            44.187513
                   ...
Liechtenstein    76.288354
Guernsey         76.995827
Andorra          77.991046
San Marino       77.997265
Monaco           78.048231
Name: Esperanza_De_Vida, Length: 247, dtype: float64